-- VHDL wrapper for NiFpgaAG_fpga_top
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 1 base clock cycles.
--               Minimum de-assertion length: 80 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_tlast : Top level indicator "tlast", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_01_tvalid : Top level indicator "tvalid", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_02_tdata : Top level indicator "tdata", sync to Clk40Derived2x1I0MHz, u8
-- ctrlind_03_MAC_Address : Top level control "MAC Address", sync to Clk40Derived2x1I0MHz, array
-- ctrlind_04_IP_Address : Top level control "IP Address", sync to Clk40Derived2x1I0MHz, array
-- ctrlind_05_Dest_Port : Top level control "Dest Port", sync to Clk40Derived2x1I0MHz, u16
-- ctrlind_06_data_in : Top level control "data_in", sync to Clk40Derived2x1I0MHz, u8
-- ctrlind_07_data_valid_in : Top level control "data_valid_in", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_08_end_of_frame_in : Top level control "end_of_frame_in", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_09_out_2 : Top level indicator "out_2", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_10_out_1 : Top level indicator "out_1", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_11_in_2 : Top level control "in_2", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_12_in_1 : Top level control "in_1", sync to Clk40Derived2x1I0MHz, bool
-- Clk40Derived2x1I0MHz : Clock "80MHz", nominal frequency 80.00 MHz, base clock

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_fpga_top is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_tlast : out std_logic_vector(0 downto 0);
			ctrlind_01_tvalid : out std_logic_vector(0 downto 0);
			ctrlind_02_tdata : out std_logic_vector(7 downto 0);
			ctrlind_03_MAC_Address : in std_logic_vector(47 downto 0);
			ctrlind_04_IP_Address : in std_logic_vector(31 downto 0);
			ctrlind_05_Dest_Port : in std_logic_vector(15 downto 0);
			ctrlind_06_data_in : in std_logic_vector(7 downto 0);
			ctrlind_07_data_valid_in : in std_logic_vector(0 downto 0);
			ctrlind_08_end_of_frame_in : in std_logic_vector(0 downto 0);
			ctrlind_09_out_2 : out std_logic_vector(0 downto 0);
			ctrlind_10_out_1 : out std_logic_vector(0 downto 0);
			ctrlind_11_in_2 : in std_logic_vector(0 downto 0);
			ctrlind_12_in_1 : in std_logic_vector(0 downto 0);
			Clk40Derived2x1I0MHz : in std_logic
		);
end NiFpgaIPWrapper_fpga_top;

architecture vhdl_labview of NiFpgaIPWrapper_fpga_top is

	component NiFpgaAG_fpga_top
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_tlast : out std_logic_vector(0 downto 0);
			ctrlind_01_tvalid : out std_logic_vector(0 downto 0);
			ctrlind_02_tdata : out std_logic_vector(7 downto 0);
			ctrlind_03_MAC_Address : in std_logic_vector(47 downto 0);
			ctrlind_04_IP_Address : in std_logic_vector(31 downto 0);
			ctrlind_05_Dest_Port : in std_logic_vector(15 downto 0);
			ctrlind_06_data_in : in std_logic_vector(7 downto 0);
			ctrlind_07_data_valid_in : in std_logic_vector(0 downto 0);
			ctrlind_08_end_of_frame_in : in std_logic_vector(0 downto 0);
			ctrlind_09_out_2 : out std_logic_vector(0 downto 0);
			ctrlind_10_out_1 : out std_logic_vector(0 downto 0);
			ctrlind_11_in_2 : in std_logic_vector(0 downto 0);
			ctrlind_12_in_1 : in std_logic_vector(0 downto 0);
			Clk40Derived2x1I0MHz : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_fpga_top
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_tlast => ctrlind_00_tlast,
			ctrlind_01_tvalid => ctrlind_01_tvalid,
			ctrlind_02_tdata => ctrlind_02_tdata,
			ctrlind_03_MAC_Address => ctrlind_03_MAC_Address,
			ctrlind_04_IP_Address => ctrlind_04_IP_Address,
			ctrlind_05_Dest_Port => ctrlind_05_Dest_Port,
			ctrlind_06_data_in => ctrlind_06_data_in,
			ctrlind_07_data_valid_in => ctrlind_07_data_valid_in,
			ctrlind_08_end_of_frame_in => ctrlind_08_end_of_frame_in,
			ctrlind_09_out_2 => ctrlind_09_out_2,
			ctrlind_10_out_1 => ctrlind_10_out_1,
			ctrlind_11_in_2 => ctrlind_11_in_2,
			ctrlind_12_in_1 => ctrlind_12_in_1,
			Clk40Derived2x1I0MHz => Clk40Derived2x1I0MHz,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

