-- VHDL wrapper for NiFpgaAG_orderbook
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 1 base clock cycles.
--               Minimum de-assertion length: 80 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_Reset : Top level control "Reset", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_01_Ready_For_OrderBook_Result : Top level control "Ready.For.OrderBook.Result", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_02_OrderBook_Command : Top level control "OrderBook.Command", sync to Clk40Derived2x1I0MHz, cluster
-- ctrlind_03_OrderBook_Command_Valid : Top level control "OrderBook.Command.Valid", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_04_OrderBook_Variables : Top level indicator "OrderBook.Variables", sync to Clk40Derived2x1I0MHz, cluster
-- ctrlind_05_OrderBook_Entry : Top level indicator "OrderBook.Entry", sync to Clk40Derived2x1I0MHz, cluster
-- ctrlind_06_Ready_For_OrderBook_Command : Top level indicator "Ready.For.OrderBook.Command", sync to Clk40Derived2x1I0MHz, bool
-- ctrlind_07_OrderBook_Result_Valid : Top level indicator "OrderBook.Result.Valid", sync to Clk40Derived2x1I0MHz, bool
-- Clk40Derived2x1I0MHz : Clock "80MHz", nominal frequency 80.00 MHz, base clock

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_orderbook is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_Reset : in std_logic_vector(0 downto 0);
			ctrlind_01_Ready_For_OrderBook_Result : in std_logic_vector(0 downto 0);
			ctrlind_02_OrderBook_Command : in std_logic_vector(311 downto 0);
			ctrlind_03_OrderBook_Command_Valid : in std_logic_vector(0 downto 0);
			ctrlind_04_OrderBook_Variables : out std_logic_vector(1046 downto 0);
			ctrlind_05_OrderBook_Entry : out std_logic_vector(311 downto 0);
			ctrlind_06_Ready_For_OrderBook_Command : out std_logic_vector(0 downto 0);
			ctrlind_07_OrderBook_Result_Valid : out std_logic_vector(0 downto 0);
			Clk40Derived2x1I0MHz : in std_logic
		);
end NiFpgaIPWrapper_orderbook;

architecture vhdl_labview of NiFpgaIPWrapper_orderbook is

	component NiFpgaAG_orderbook
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_Reset : in std_logic_vector(0 downto 0);
			ctrlind_01_Ready_For_OrderBook_Result : in std_logic_vector(0 downto 0);
			ctrlind_02_OrderBook_Command : in std_logic_vector(311 downto 0);
			ctrlind_03_OrderBook_Command_Valid : in std_logic_vector(0 downto 0);
			ctrlind_04_OrderBook_Variables : out std_logic_vector(1046 downto 0);
			ctrlind_05_OrderBook_Entry : out std_logic_vector(311 downto 0);
			ctrlind_06_Ready_For_OrderBook_Command : out std_logic_vector(0 downto 0);
			ctrlind_07_OrderBook_Result_Valid : out std_logic_vector(0 downto 0);
			Clk40Derived2x1I0MHz : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_orderbook
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_Reset => ctrlind_00_Reset,
			ctrlind_01_Ready_For_OrderBook_Result => ctrlind_01_Ready_For_OrderBook_Result,
			ctrlind_02_OrderBook_Command => ctrlind_02_OrderBook_Command,
			ctrlind_03_OrderBook_Command_Valid => ctrlind_03_OrderBook_Command_Valid,
			ctrlind_04_OrderBook_Variables => ctrlind_04_OrderBook_Variables,
			ctrlind_05_OrderBook_Entry => ctrlind_05_OrderBook_Entry,
			ctrlind_06_Ready_For_OrderBook_Command => ctrlind_06_Ready_For_OrderBook_Command,
			ctrlind_07_OrderBook_Result_Valid => ctrlind_07_OrderBook_Result_Valid,
			Clk40Derived2x1I0MHz => Clk40Derived2x1I0MHz,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

