@startuml High_Level (Expanded)

title High Level (Detailed)

skinparam handwritten true
left to right direction

state "Ethernet" as ethernet: PHY
state "Ethernet" as ethernet: SFP+
state "Ethernet" as ethernet: QSFP+

state "UDP/IP Parser" as Udp_Ip

state "Feed Handler" as Feed_Handler {
    state "BATS PITCH" as Bats_Parser
    state "Nasdaq ITCH" as Itch_Parser
}

state "Feed Arbitrator" as Feed_Arb
state "Command Arbitrator" as Command_Arb
state "App Request" as App_Request
state "OrderBook" as OrderBook
state "Memory" as Memory

[*] --> ethernet
ethernet --> Udp_Ip

Udp_Ip --> Bats_Parser
Udp_Ip --> Itch_Parser

Bats_Parser --> Feed_Arb
Itch_Parser --> Feed_Arb

Feed_Arb -> Command_Arb
App_Request --> Command_Arb
Command_Arb --> OrderBook

OrderBook -> Memory

@enduml