@startuml Part 5: Application

title Part 5: Application

skinparam handwritten true
left to right direction

skinparam cloud {
    handwritten false
}

actor "App Request" as App
node "Arbitrator" as Arbitrator
node "Order Book" as OrderBook
database "Block RAM" as Memory

Arbitrator <-- App
Arbitrator -> OrderBook
OrderBook -> Memory

@enduml