@startuml Part 4: Order Book

title Part 4: Order Book

skinparam handwritten true
left to right direction

skinparam cloud {
    handwritten false
}

state "BATS Normalizer" as BATS
state "NASDAQ Normalizer" as NASDAQ
state "Normalized Messages" as Normalized
'node "Order Book Processor" as OrderBook
'node OrderBook
'database "Block RAM" as Memory

'Normalized --> OrderBook
'OrderBook -> Memory

@enduml