@startuml Part 3: NASDAQ

title Part 3: NASDAQ ITCH Parser/Normalizer

skinparam handwritten true
left to right direction

skinparam cloud {
    handwritten false
}

' inputs
'  Normalized OrderBook Message
' Outputs:
'   Write response to buffer (if required)
cloud "NASDAQ ITCH Market Data Messages" as Data
node "NASDAQ Parser/Normalizer" as Normalizer
cloud "Normalized Messages" as Normalized

Data --> Normalizer
Normalizer--> Normalized

@enduml